version: '2.1'
services:
    pdv-app:
        image: pdvapp
        ports:
            - 8080:8080
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=pdv
        depends_on:
            mongodb:
                condition: service_healthy
        restart: always

    mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            timeout: 5s
            retries: 10
        restart: always
